name: CI for order service
on:
  pull_request:
    branches: [  "order-service" ] # do tests on prs on order-service
    paths:
      - 'order-service/**' # track only on order service changes

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Start Google Firestore emulator
      run: |
        docker run -d \
          --name firestore-emulator \
          -p 8085:8085 \
          gcr.io/google.com/cloudsdktool/cloud-sdk:emulators \
          gcloud beta emulators firestore start --host-port=0.0.0.0:8085
    
    - name: Wait for Firestore emulator
      run: |
        echo "Waiting for Firestore emulator to be ready..."
        sudo apt-get update && sudo apt-get install -y curl
        timeout 60s bash -c 'until curl -f http://localhost:8085; do sleep 2; done'
        echo "Firestore emulator is ready!"
    
    - name: Install dependencies (orders)
      working-directory: order-service
      run: |
        python -m pip install -r requirements/dev.txt
    
    - name: Lint & Unit Test (orders)
      working-directory: order-service
      env:
        FIRESTORE_EMULATOR_HOST: localhost:8085
        GCLOUD_PROJECT: test-project
      run: |
        pytest -q
    
    - name: Clean up
      if: always()
      run: docker rm -f firestore-emulator